import type { ConfigProviderProps } from 'antdv-next'
import { theme } from 'antdv-next'
import { computed } from 'vue'

const useGlassTheme = () => computed<ConfigProviderProps>(() => ({
    theme: {
                    algorithm: theme.defaultAlgorithm,
                    token: {
                        borderRadius: 12,
                        borderRadiusLG: 12,
                        borderRadiusSM: 12,
                        borderRadiusXS: 12,
                        motionDurationSlow: '0.2s',
                        motionDurationMid: '0.1s',
                        motionDurationFast: '0.05s',
                    },
                    components: {
                        Button: {
                            primaryShadow: 'none',
                            dangerShadow: 'none',
                            defaultShadow: 'none',
                            colorError: '#ff7875',
                            colorErrorHover: '#ffa39e',
                            colorErrorActive: '#ff4d4f',
                            colorErrorBg: 'rgba(255, 120, 117, 0.1)',
                            colorErrorBgFilledHover: 'rgba(255, 120, 117, 0.16)',
                            colorErrorBgActive: 'rgba(255, 120, 117, 0.12)',
                            colorErrorBorder: 'rgba(255, 120, 117, 0.24)',
                            colorErrorBorderHover: 'rgba(255, 120, 117, 0.32)',
                            colorErrorText: '#ff7875',
                            colorErrorTextHover: '#ffa39e',
                            colorErrorTextActive: '#ff4d4f',
                            defaultBg: 'rgba(255, 255, 255, 0.1)',
                            defaultBorderColor: 'rgba(255, 255, 255, 0.1)',
                            defaultHoverBg: 'rgba(255, 255, 255, 0.2)',
                            defaultHoverBorderColor: 'rgba(255, 255, 255, 0.1)',
                            defaultActiveBg: 'rgba(255, 255, 255, 0.1)',
                            defaultActiveBorderColor: 'rgba(255, 255, 255, 0.18)',
                        },
                        Notification: {
                            colorSuccessBg: 'rgba(183, 235, 143, 0.18)',
                            colorErrorBg: 'rgba(255, 120, 117, 0.16)',
                            colorInfoBg: 'rgba(145, 202, 255, 0.18)',
                            colorWarningBg: 'rgba(255, 229, 143, 0.18)',
                        },
                        Layout: {
                            bodyBg: 'rgba(255, 255, 255, 0.12)',
                            footerBg: 'rgba(255, 255, 255, 0.12)',
                            headerBg: 'rgba(255, 255, 255, 0.32)',
                            headerColor: 'rgba(0, 0, 0, 0.88)',
                            siderBg: 'rgba(255, 255, 255, 0.18)',
                            triggerBg: 'rgba(255, 255, 255, 0.28)',
                            triggerColor: 'rgba(0, 0, 0, 0.88)',
                        },
                        Menu: {
                            activeBarBorderWidth: 0,
                            groupTitleColor: 'rgba(0, 0, 0, 0.55)',
                            itemActiveBg: 'rgba(255, 255, 255, 0.24)',
                            itemBg: 'transparent',
                            itemColor: 'rgba(0, 0, 0, 0.78)',
                            itemHoverBg: 'rgba(255, 255, 255, 0.28)',
                            itemHoverColor: 'rgba(0, 0, 0, 0.88)',
                            itemSelectedBg: 'color-mix(in srgb, #1677ff 18%, transparent)',
                            itemSelectedColor: '#1677ff',
                            subMenuItemBg: 'transparent',
                            subMenuItemSelectedColor: 'rgba(0, 0, 0, 0.88)',
                        },
                        Alert: {},
                        Modal: {},
                        Card: {},
                        Tooltip: {},
                        Checkbox: {},
                        Radio: {},
                        Select: {},
                        Input: {},
                        Switch: {},
                        Progress: {
                            circleTextColor: 'rgba(0, 0, 0, 0.88)',
                            defaultColor: '#1677ff',
                            remainingColor: 'rgba(255, 255, 255, 0.28)',
                        },
                        Steps: {},
                        Slider: {},
                        ColorPicker: {},
                    },
                },
}))

export default useGlassTheme
